### ISSUE TITLE
500 with image component in model

### ISSUE THREAD

**Issue by thousandsofraccoons** [MaksZhukov/strapi-plugin-generate-data#12]
Hello, trying to generate data on localhost. Getting internal server error as a response if the model has an image component in it
![image](https://user-images.githubusercontent.com/33694447/181711325-3d6792a1-ceeb-4ed2-85d1-1f07f5a0d07f.png)

P.S. Also it doesn't fill relations and some fields (it simply doesn't appear in the UI as an option)

**Comment by MaksZhukov** [comment]
@thousandsofraccoons Hey! Could you share the screen in nodejs console in that moment?
According to fields support
![image](https://user-images.githubusercontent.com/23615115/181720815-a08b1afb-e3d2-4aa1-a99e-c8b3aea059bc.png)
For the other fields its for future plans

**Comment by MaksZhukov** [comment]
@thousandsofraccoons Hey! Do you have any updates?

**Comment by Chiliseo** [comment]
<img width="772" alt="image" src="https://user-images.githubusercontent.com/3642182/183256656-941af81d-f26c-4213-9bbc-1944d61a3cb4.png">
maybe the issue is like firt we need to upload the images becuase the categories only work with id images

**Comment by Chiliseo** [comment]
this is an example insert to category with image
<img width="749" alt="image" src="https://user-images.githubusercontent.com/3642182/183256773-b2dd1f53-a420-43ba-a2a9-63a890059349.png">

**Comment by Chiliseo** [comment]
I fixed using the token on request
<img width="863" alt="image" src="https://user-images.githubusercontent.com/3642182/183259140-756c53cc-9ae0-4d20-82d7-a44fa268afc6.png">

**Comment by MaksZhukov** [comment]
Thanks, I will check

**Comment by MaksZhukov** [comment]
@Chiliseo @thousandsofraccoons Hey! Could you check in the tag https://github.com/MaksZhukov/strapi-plugin-generate-data/releases/tag/v1.0.13?

**Comment by Chiliseo** [comment]
Awesome I tested and work nice, Excellent @MaksZhukov  
<img width="845" alt="Screen Shot 2022-08-10 at 8 15 51 AM" src="https://user-images.githubusercontent.com/3642182/183924101-e61c5844-3409-4786-9a11-8352b4a73234.png">
