### ISSUE TITLE
Long text is not appearing in fields when creating data

### ISSUE THREAD

**Issue by rawestmoreland** [MaksZhukov/strapi-plugin-generate-data#22]
When I go to create data, my `Long Text` fields are not appearing in the UI. For example, if I have a field called `description` and it's `Long Text`, I do not see it when generating data. I only see `Short Text` fields.

**Comment by MaksZhukov** [comment]
@rawestmoreland Hey, thanks for the noticing. will resolve it in next release

**Comment by rawestmoreland** [comment]
Thanks @MaksZhukov ! I found the issue and can open a PR if that would be helpful.

**Comment by rawestmoreland** [comment]
https://github.com/MaksZhukov/strapi-plugin-generate-data/pull/23

**Comment by MaksZhukov** [comment]
@rawestmoreland Try it in new release!

**Comment by rawestmoreland** [comment]
Yep it's working! Thanks for letting me contribute. I see some issues with datetime, (date works well, just not recognizing datetime) so I may try and work on that as well.

**Comment by MaksZhukov** [comment]
> Yep it's working! Thanks for letting me contribute. I see some issues with datetime, (date works well, just not recognizing datetime) so I may try and work on that as well.

Thanks, sure. I would be very grateful
