### ISSUE TITLE
Install error - Cannot find module @strapi/design-system

### ISSUE THREAD

**Issue by Arrig0** [MaksZhukov/strapi-plugin-generate-data#31]
System Information:
Strapi: 4.5.1 
Node: v14.20.0
OS: Ubuntu 20.04.2 LTS
Yarn: 1.22.19
Npm: 6.14.17

I'm unable to install this plugin.
`
error in strapi-plugin-generate-data: Command failed.
Exit code: 2
Command: tsc
Output:
admin/src/components/GeneratedDataTable/GeneratedDataTable.tsx(3,49): error TS2307: Cannot find module '@strapi/design-system/Table' or its corresponding type declarations.
`

Last message repeated for each design system component

**Comment by MaksZhukov** [comment]
@Arrig0 Hey! Thanks, I will investigate it

**Comment by Arrig0** [comment]
Thanks.

**Comment by MaksZhukov** [comment]
@Arrig0 Could you try with new version?

**Comment by Arrig0** [comment]
Sure @MaksZhukov !
Unluckily there are still problems.
I added the develop branch with..
yarn add https://github.com/MaksZhukov/strapi-plugin-generate-data.git#develop
then i run the build process.

Following the full output:

`
arrigo@blacky:~/public_html/zerokids$ yarn build
yarn run v1.22.19
$ strapi build
Starting the compilation for TypeScript files in /home/arrigo/public_html/zerokids
Building your admin UI with development configuration...

● Webpack █████████████████████████ building (58%) 1/1 entries 2719/3081 dependencies 619/1279 modules 324 active 
 node_modules/react-query/lib/core/mutationObserver.js

ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/icons/CarretDown' in '/home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/dist/Select'
Did you mean 'CarretDown.js'?
BREAKING CHANGE: The request '@strapi/icons/CarretDown' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/arrigo/public_html/zerokids/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/home/arrigo/public_html/zerokids/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve '@strapi/icons/CarretDown' in '/home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/dist/Select'
  Parsed request is a module
  using description file: /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/package.json (relative path: ./dist/Select)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/dist/Select/node_modules doesn't exist or is not a directory
      /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/dist/node_modules doesn't exist or is not a directory
      looking for modules in /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/node_modules
        existing directory /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/node_modules/@strapi/icons
          using description file: /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/node_modules/@strapi/icons/package.json (relative path: .)
            using exports field: ./dist/CarretDown
              using description file: /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/node_modules/@strapi/icons/package.json (relative path: ./dist/CarretDown)
                Field 'browser' doesn't contain a valid alias configuration
                /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/node_modules/@strapi/icons/dist/CarretDown doesn't exist
      /home/arrigo/public_html/zerokids/node_modules/@strapi/node_modules doesn't exist or is not a directory
      /home/arrigo/public_html/zerokids/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/arrigo/public_html/zerokids/node_modules
        existing directory /home/arrigo/public_html/zerokids/node_modules/@strapi/icons
          using description file: /home/arrigo/public_html/zerokids/node_modules/@strapi/icons/package.json (relative path: .)
            using description file: /home/arrigo/public_html/zerokids/node_modules/@strapi/icons/package.json (relative path: ./CarretDown)
              Field 'browser' doesn't contain a valid alias configuration
              /home/arrigo/public_html/zerokids/node_modules/@strapi/icons/CarretDown doesn't exist
      /home/arrigo/public_html/node_modules doesn't exist or is not a directory
      looking for modules in /home/arrigo/node_modules
        /home/arrigo/node_modules/@strapi/icons doesn't exist
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/arrigo/public_html/zerokids/node_modules/@strapi/admin/node_modules
        /home/arrigo/public_html/zerokids/node_modules/@strapi/admin/node_modules/@strapi/icons doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve '@strapi/icons/CarretDown' in '/home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/dist/Select'
Did you mean 'CarretDown.js'?
BREAKING CHANGE: The request '@strapi/icons/CarretDown' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/Compilation.js:2016:28
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/home/arrigo/public_html/zerokids/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/home/arrigo/public_html/zerokids/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /home/arrigo/public_html/zerokids/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve '@strapi/icons/CarretDown' in '/home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/dist/Select'
  Parsed request is a module
  using description file: /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/package.json (relative path: ./dist/Select)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/dist/Select/node_modules doesn't exist or is not a directory
      /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/dist/node_modules doesn't exist or is not a directory
      looking for modules in /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/node_modules
        existing directory /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/node_modules/@strapi/icons
          using description file: /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/node_modules/@strapi/icons/package.json (relative path: .)
            using exports field: ./dist/CarretDown
              using description file: /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/node_modules/@strapi/icons/package.json (relative path: ./dist/CarretDown)
                Field 'browser' doesn't contain a valid alias configuration
                /home/arrigo/public_html/zerokids/node_modules/@strapi/design-system/node_modules/@strapi/icons/dist/CarretDown doesn't exist
      /home/arrigo/public_html/zerokids/node_modules/@strapi/node_modules doesn't exist or is not a directory
      /home/arrigo/public_html/zerokids/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /home/arrigo/public_html/zerokids/node_modules
        existing directory /home/arrigo/public_html/zerokids/node_modules/@strapi/icons
          using description file: /home/arrigo/public_html/zerokids/node_modules/@strapi/icons/package.json (relative path: .)
            using description file: /home/arrigo/public_html/zerokids/node_modules/@strapi/icons/package.json (relative path: ./CarretDown)
              Field 'browser' doesn't contain a valid alias configuration
              /home/arrigo/public_html/zerokids/node_modules/@strapi/icons/CarretDown doesn't exist
      /home/arrigo/public_html/node_modules doesn't exist or is not a directory
      looking for modules in /home/arrigo/node_modules
        /home/arrigo/node_modules/@strapi/icons doesn't exist
      /home/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /home/arrigo/public_html/zerokids/node_modules/@strapi/admin/node_modules
        /home/arrigo/public_html/zerokids/node_modules/@strapi/admin/node_modules/@strapi/icons doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

`

**Comment by MaksZhukov** [comment]
@Arrig0 So what i see, there is no error from strapi-plugin-generate-data. Maybe could you reinstall node_modules, delete package-lock.json and run npm run cache clean
or try with fresh strapi project

**Comment by Flaex** [comment]
Same problem here but using yarn. I tried deleting .cache, node_modules folder and yarn.lock file without success.
Please let us know if there is some workaround or fix.
Thank you!

**Comment by MaksZhukov** [comment]
@Flaex Hey! Could you give me your environment for it and the error, i will investigate

**Comment by Arrig0** [comment]
Updating to strapi 4.5.3 solve this issue.

**Comment by Flaex** [comment]
@MaksZhukov Hi!
This is my system Information:
Strapi: 4.5.3
Node: v16.18.1
OS: Fedora 36
Yarn: 1.22.19
Npm: 8.19.2

As suggested by @Arrig0, I tried updating to Strapi v4.5.3 but the error is different from the original:

```
$ strapi develop
Building your admin UI with development configuration...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1098:7)
    at /mnt/EC088AC8088A90EE/repos/cms-be/node_modules/@strapi/admin/utils/create-cache-dir.js:82:33
    at Array.filter (<anonymous>)
    at createCacheDir (/mnt/EC088AC8088A90EE/repos/cms-be/node_modules/@strapi/admin/utils/create-cache-dir.js:80:6)
    at async Object.build (/mnt/EC088AC8088A90EE/repos/cms-be/node_modules/@strapi/admin/index.js:27:3)
    at async primaryProcess (/mnt/EC088AC8088A90EE/repos/cms-be/node_modules/@strapi/strapi/lib/commands/develop.js:62:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Should I open a new issue about this?
