### ISSUE TITLE
It would be amazing to have this working with node 18.x

### ISSUE THREAD

**Issue by alexbudin** [MaksZhukov/strapi-plugin-generate-data#34]
Strapi now supports Node 18.x (with npm v6 still).

Any chance we would get an update of this plugin?

Great plugin by the way!

Thank you,

Alex

**Comment by MaksZhukov** [comment]
@alexbudin Hey! Will update soon.
Thanks)

**Comment by MaksZhukov** [comment]
@alexbudin Hey! It's updated in the latest version
