### ISSUE TITLE
not working at all...

### ISSUE THREAD

**Issue by selfagency** [MaksZhukov/strapi-plugin-generate-data#39]
plugin version: 1.0.23
strapi version: 4.12.1
node version: 18.17.0

![CleanShot 2023-08-04 at 20 26 58](https://github.com/MaksZhukov/strapi-plugin-generate-data/assets/2541728/bbe12344-d235-4bae-9be8-5eacad22ab21)

`plugin.ts`:

```
module.exports = ({ env }) => ({
  sentry: {
    enabled: false,
    config: {
      dsn: env("SENTRY_DSN"),
      sendMetadata: true,
    },
  },
  "generate-data": {
    enabled: true,
  },
});
```

`middleware.ts`:

```
export default [
  "strapi::errors",
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": ["'self'", "data:", "blob:", `https://loremflickr.com/`],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
  {
    name: "strapi::cors",
    config: {
      origin: ["http://localhost:1337", "http://localhost:4000"],
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
      headers: ["*"],
      keepHeaderOnError: true,
    },
  },
  "strapi::poweredBy",
  "strapi::logger",
  "strapi::query",
  "strapi::body",
  "strapi::session",
  "strapi::favicon",
  "strapi::public",
];
```

**Comment by MaksZhukov** [comment]
@selfagency Hey! Thanks for a good catch, will check
Also do you have any errors in a console?

**Comment by MaksZhukov** [comment]
@selfagency Hey!
This is what i have, i tried with typescript and without and i don't have plugins file, it automatically enabled
![image](https://github.com/MaksZhukov/strapi-plugin-generate-data/assets/23615115/1a66dcc9-5626-4cb0-98c5-06b3503c352a)
![image](https://github.com/MaksZhukov/strapi-plugin-generate-data/assets/23615115/7b86107d-8c7a-42ae-8fe7-4aea66360505)
![image](https://github.com/MaksZhukov/strapi-plugin-generate-data/assets/23615115/b48beb3b-7284-411e-9beb-e1d2998490b2)

**Comment by ZayneLiu** [comment]
@selfagency 
I ran into the same issue, and the issue seems to be the admin UI is not rebuilding as expected.

try remove existing `dist` directory to force a admin UI rebuild.

**Comment by selfagency** [comment]
thank you, @ZayneLiu, you are 100% correct. i just had to run `strapi build` and i showed up.

**Comment by carlosromanxyz** [comment]
Hi @MaksZhukov

I solved this issue following these steps:

**IMPORTANT:**

If you Dockerize Strapi App, you need use Docker Terminal instead VSCode (or Mac/Windows Terminal), if you use Docker GUI open terminal, if you use Orbstack (or another), open Terminal.

1.- Use Node 16 or 18
2.- Create Strapi app
3.- Install the plugin
4.- Add the config/plugins file if not exist and add recomended lines from plugin author
5.- REbuild admin UI using `strapi build` command... again, on Docker Terminal
6.- Excuse my english :)

Regards.

**Comment by MaksZhukov** [comment]
@selfagency @carlosromanxyz Hey!Thanks! I've added about it to ReadMe.
