### ISSUE TITLE
Count items to generate has crashed app from item 25

### ISSUE THREAD

**Issue by chungnq253** [MaksZhukov/strapi-plugin-generate-data#41]
https://github.com/MaksZhukov/strapi-plugin-generate-data/assets/44595953/f3718985-47dc-46f7-b84b-6877e4578e75

<img width="1548" alt="image" src="https://github.com/MaksZhukov/strapi-plugin-generate-data/assets/44595953/7f0b0668-771b-4b96-936a-5e72b1b13d25">

**Comment by MaksZhukov** [comment]
@chungnq253 Hey! Thanks for reporting the bug, will check and update soon!

**Comment by MaksZhukov** [comment]
@chungnq253  Hey! Could you check the latest version?

**Comment by chungnq253** [comment]
Look good to me now, thanks for your update @MaksZhukov 😉
