### ISSUE TITLE
Feature - Generate Dates

### ISSUE THREAD

**Issue by heyjaypray** [MaksZhukov/strapi-plugin-generate-data#55]
Would be cool to have a date selector where you can select min and max dates for date fields

**Comment by MaksZhukov** [comment]
@heyjaypray Hey! Date selectors **from** and **to** are already implemented.
![image](https://github.com/MaksZhukov/strapi-plugin-generate-data/assets/23615115/337cd483-615c-4af6-bb97-de8b9363d51f)
![image](https://github.com/MaksZhukov/strapi-plugin-generate-data/assets/23615115/1255be24-a4be-497d-b8d3-a087378e62d7)

**Comment by heyjaypray** [comment]
Must've missed it!  Thank you for your work!
