### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by creaux** [MaksZhukov/strapi-plugin-generate-data#58]
I'm able to generate but when I trigger to upload. Request-Response bellow.

What is strange in the response is `Allow: HEAD, GET`.

Request Headers

```
POST /generate-data/create/api::post.post HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: cs-CZ,cs;q=0.9,en;q=0.8,de;q=0.7
Authorization: Bearer <token>
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 1434
Content-Type: application/json
Host: 127.0.0.1:1337
Origin: http://127.0.0.1:1337
Pragma: no-cache
Referer: http://127.0.0.1:1337/admin/plugins/generate-data?typeUID=api%3A%3Apost.post
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
```

Response Headers

```
HTTP/1.1 405 Method Not Allowed
Content-Security-Policy: connect-src 'self' https:;img-src 'self' data: blob: res.cloudinary.com lh3.googleusercontent.com platform-lookaside.fbsbx.com dl.airtable.com https://undefined.s3.undefined.amazonaws.com https://loremflickr.com/;media-src 'self' data: blob: https://undefined.s3.undefined.amazonaws.com https://loremflickr.com/;default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'
Referrer-Policy: no-referrer
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
Vary: Origin
Access-Control-Allow-Origin: http://127.0.0.1:1337
Access-Control-Allow-Credentials: true
Allow: HEAD, GET
X-Powered-By: Strapi <strapi.io>
Content-Type: text/plain; charset=utf-8
Content-Length: 18
Date: Fri, 12 Jul 2024 20:55:13 GMT
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by MaksZhukov** [comment]
@creaux Hey! Could you provide the strapi version and some screenshots from UI?
What came in my mind that for your entity you don't have permissions to create(do POST) request
The feature should on settings page like permissions

**Comment by creaux** [comment]
Hi @MaksZhukov,  version is 4.25.1.

I'm using super admin user so I suppose all should be supported. 

![image](https://github.com/user-attachments/assets/a18d6959-f5c2-4bbe-a50d-8c177a7fe48c)

**Comment by MaksZhukov** [comment]
@creaux 
I tried to do it on my machine and it works
![Screenshot 2024-07-17 005623](https://github.com/user-attachments/assets/ec29c36b-eee7-4458-9e4a-5e9e91dfb636)
![Screenshot 2024-07-17 005651](https://github.com/user-attachments/assets/cab2cb38-874d-4235-9310-5127ba0072d1)
![Screenshot 2024-07-17 005808](https://github.com/user-attachments/assets/a00fe77f-ca55-4b51-9ebc-8056c38be6f0)
![Screenshot 2024-07-17 005602](https://github.com/user-attachments/assets/b90cfaf7-88cd-417f-bf71-293b20c2b8ca)
![image](https://github.com/user-attachments/assets/87333689-2aaa-4137-b5f3-f7b887dcb4d3)
![image](https://github.com/user-attachments/assets/830c9890-4eac-476a-bed5-cf4c4a0023eb)

Do you have any policies for your entity(**post**) or middleware?
https://docs.strapi.io/dev-docs/backend-customization/policies
